//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderDeliveryMonitor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderDeliveryMonitor.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardo_Fim.
        /// </summary>
        public static string CLM_AWAITING_END {
            get {
                return ResourceManager.GetString("CLM_AWAITING_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardo_Inicio.
        /// </summary>
        public static string CLM_AWAITING_START {
            get {
                return ResourceManager.GetString("CLM_AWAITING_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caixa_Codigo.
        /// </summary>
        public static string CLM_CASHIER_CODE {
            get {
                return ResourceManager.GetString("CLM_CASHIER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string CLM_CODE {
            get {
                return ResourceManager.GetString("CLM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando.
        /// </summary>
        public static string CLM_COMMAND {
            get {
                return ResourceManager.GetString("CLM_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido_Codigo.
        /// </summary>
        public static string CLM_ORDER_CODE {
            get {
                return ResourceManager.GetString("CLM_ORDER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo_Busca.
        /// </summary>
        public static string CLM_ORDER_IDENTIFICATION {
            get {
                return ResourceManager.GetString("CLM_ORDER_IDENTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        public static string CLM_ORDER_NUMBER {
            get {
                return ResourceManager.GetString("CLM_ORDER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparo_Fim.
        /// </summary>
        public static string CLM_PREPARING_END {
            get {
                return ResourceManager.GetString("CLM_PREPARING_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparo_Inicio.
        /// </summary>
        public static string CLM_PREPARING_START {
            get {
                return ResourceManager.GetString("CLM_PREPARING_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string CLM_PROCESS {
            get {
                return ResourceManager.GetString("CLM_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto_Nome.
        /// </summary>
        public static string CLM_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("CLM_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string CLM_QUANTITY {
            get {
                return ResourceManager.GetString("CLM_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronto_Fim.
        /// </summary>
        public static string CLM_READY_END {
            get {
                return ResourceManager.GetString("CLM_READY_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronto_Inicio.
        /// </summary>
        public static string CLM_READY_START {
            get {
                return ResourceManager.GetString("CLM_READY_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data_Resgate.
        /// </summary>
        public static string CLM_REDEEM_DATE {
            get {
                return ResourceManager.GetString("CLM_REDEEM_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal_Venda.
        /// </summary>
        public static string CLM_SALE_CHANNEL {
            get {
                return ResourceManager.GetString("CLM_SALE_CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estacao_Venda.
        /// </summary>
        public static string CLM_SELLING_STATION {
            get {
                return ResourceManager.GetString("CLM_SELLING_STATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando.
        /// </summary>
        public static string LBL_AWAITING {
            get {
                return ResourceManager.GetString("LBL_AWAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel do cliente.
        /// </summary>
        public static string LBL_CUSTOMERDASHBOARD {
            get {
                return ResourceManager.GetString("LBL_CUSTOMERDASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel de controle.
        /// </summary>
        public static string LBL_DASHBOARD {
            get {
                return ResourceManager.GetString("LBL_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LBL_LOGIN {
            get {
                return ResourceManager.GetString("LBL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparando.
        /// </summary>
        public static string LBL_PREPARING {
            get {
                return ResourceManager.GetString("LBL_PREPARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronto.
        /// </summary>
        public static string LBL_READY {
            get {
                return ResourceManager.GetString("LBL_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado.
        /// </summary>
        public static string MSG_RECORDS_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_RECORDS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido.
        /// </summary>
        public static string TBL_ORDER {
            get {
                return ResourceManager.GetString("TBL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PedidoItem.
        /// </summary>
        public static string TBL_ORDER_ITEM {
            get {
                return ResourceManager.GetString("TBL_ORDER_ITEM", resourceCulture);
            }
        }
    }
}
